import Link from "next/link";
import { ArrowRight, CircleAlert, CircleCheck, Clock3 } from "lucide-react";
import type { WorkspaceOverview } from "@/lib/workspace";
import { workspaceHref } from "@/lib/workspace";
import { formatDateTime } from "@/lib/format";
import { buttonVariants } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { StatusPill } from "@/components/app/status";
import { CountUp } from "@/components/motion/count-up";
import { ProgressFill } from "@/components/motion/progress-fill";

/** The task list: the first `limit` tasks, or all of them when `expanded` (Beranda's `?tugas=semua`); one page, two lengths. */
export function WorkspaceTasks({ data, limit, expanded = false }: { data: WorkspaceOverview; limit?: number; expanded?: boolean }) {
  const tasks = limit && !expanded ? data.tasks.slice(0, limit) : data.tasks;
  const more = limit !== undefined && data.tasks.length > limit;
  return <Card><CardHeader className="flex flex-row flex-wrap items-center justify-between gap-3"><div><CardTitle role="heading" aria-level={2}>Perlu dikerjakan</CardTitle><CardDescription>Masalah yang menghambat buku didahulukan.</CardDescription></div>{more && <Link href={workspaceHref("/", data.scope, expanded ? {} : { tugas: "semua" })} className={buttonVariants({ variant: "ghost", size: "sm" })}>{expanded ? `Tampilkan ${limit} teratas` : `Semua pekerjaan (${data.tasks.length})`} <ArrowRight /></Link>}</CardHeader><CardContent><ul className="divide-y">{tasks.map((task) => <li key={task.id} className="flex flex-wrap items-center gap-3 py-4 first:pt-0 last:pb-0"><span className={task.priority === "high" ? "text-review" : "text-muted-foreground"}>{task.priority === "high" ? <CircleAlert className="size-5" aria-label="Prioritas tinggi" /> : <Clock3 className="size-5" aria-label="Pekerjaan berikutnya" />}</span><div className="min-w-0 flex-1"><p className="text-sm font-semibold">{task.title}</p><p className="mt-0.5 text-xs text-muted-foreground">{task.detail}</p></div><Link href={task.href} aria-label={`${task.title} · ${task.detail}`} className={buttonVariants({ variant: "outline", size: "sm" })}>Buka <ArrowRight aria-hidden /></Link></li>)}</ul>{!tasks.length && <p className="flex items-start gap-2 text-sm text-muted-foreground"><CircleCheck className="size-4 shrink-0 text-pass" />{data.clients.length ? "Tidak ada pekerjaan tertunda pada cakupan ini." : "Tambahkan klien untuk mulai menyiapkan buku."}</p>}</CardContent></Card>;
}

type BoardClient = WorkspaceOverview["clients"][number];

/** Papan kantor (I5a, ADR 0014): every client's month by stage — Sumber, Review, Tutup buku, Terkirim. Each cell links to where it is fixed. */
export function WorkspaceClose({ data }: { data: WorkspaceOverview }) {
  const { closed, clients } = data.counts;
  const cells = (c: BoardClient) => [
    { label: "Sumber", node: !c.sumber.rows ? <span className="text-xs text-muted-foreground">Belum ada data</span> : <Link href={c.importHref}><StatusPill status={c.sumber.gaps ? "REVIEW" : "PASS"} label={c.sumber.gaps ? `${c.sumber.gaps} kurang` : "Lengkap"} /></Link> },
    { label: "Review", node: <Link href={c.reviewHref}><StatusPill status={c.openReview ? "REVIEW" : "PASS"} label={c.openReview ? `${c.openReview} transaksi` : "Selesai"} /></Link> },
    { label: "Tutup buku", node: <Link href={c.closeHref}><StatusPill status={c.state === "LOCKED" || c.state === "READY" ? "PASS" : c.state === "FAIL" ? "FAIL" : "REVIEW"} label={c.label} /></Link> },
    { label: "Terkirim", node: c.state !== "LOCKED" ? <span className="text-xs text-muted-foreground">–</span> : c.sentAt ? <StatusPill status="PASS" label={formatDateTime(c.sentAt)} /> : <StatusPill status="REVIEW" label="Belum dikirim" /> },
  ];
  return <Card data-testid="firm-board"><CardHeader><CardTitle role="heading" aria-level={2}>Kemajuan tutup buku</CardTitle><CardDescription>{data.scope.periodLabel} · per klien: data lengkap, review selesai, buku ditutup, laporan terkirim</CardDescription></CardHeader><CardContent className="space-y-4"><div><div className="mb-2 flex justify-between gap-2 text-sm"><span>Klien selesai</span><strong><CountUp value={closed} suffix={` / ${clients}`} /></strong></div><ProgressFill value={clients ? (closed / clients) * 100 : 0} aria-label={`${closed} dari ${clients} klien selesai tutup buku`} /></div>{data.scope.kind === "entity" && <p className="text-xs leading-relaxed text-muted-foreground">Status mencakup seluruh grup / klien induk perusahaan ini.</p>}
    <table className="hidden w-full text-sm md:table"><thead><tr className="border-b">{["Klien", "Sumber", "Review", "Tutup buku", "Terkirim"].map((h) => <th key={h} className="eyebrow py-2 pr-3 text-left font-normal">{h}</th>)}</tr></thead><tbody className="divide-y">{data.clients.map((c) => <tr key={c.id} data-testid="board-row"><td className="py-3 pr-3"><Link href={c.closeHref} className="inline-flex items-center gap-1 font-medium hover:text-primary">{c.name}<ArrowRight className="size-3.5 shrink-0" /></Link></td>{cells(c).map((cell) => <td key={cell.label} className="py-3 pr-3">{cell.node}</td>)}</tr>)}</tbody></table>
    <ul className="divide-y md:hidden">{data.clients.map((c) => <li key={c.id} className="space-y-2 py-3"><Link href={c.closeHref} className="inline-flex min-w-0 items-center gap-1 text-sm font-medium hover:text-primary">{c.name}<ArrowRight className="size-3.5 shrink-0" /></Link><dl className="grid grid-cols-2 gap-2">{cells(c).map((cell) => <div key={cell.label}><dt className="eyebrow text-muted-foreground">{cell.label}</dt><dd className="mt-1">{cell.node}</dd></div>)}</dl></li>)}</ul>
    {!clients && <p className="text-sm text-muted-foreground">Belum ada klien dalam ruang kerja ini.</p>}</CardContent></Card>;
}

export function WorkspaceFinancials({ data }: { data: WorkspaceOverview }) {
  return <Card><CardHeader><CardTitle role="heading" aria-level={2}>Keuangan per perusahaan</CardTitle><CardDescription>Dari buku besar · jurnal yang sudah dibukukan · {data.scope.periodLabel}. Setiap perusahaan memakai mata uangnya sendiri; bukan konsolidasi.</CardDescription></CardHeader><CardContent className="space-y-4">{data.entities.map((entity) => <article key={entity.id} className="rounded-lg border p-4"><div className="flex flex-wrap items-start justify-between gap-2"><div className="min-w-0"><h3 className="text-sm font-semibold"><Link className="inline-flex items-center gap-2 hover:text-primary" href={entity.reportHref}>{entity.name}<ArrowRight className="size-4 shrink-0" /></Link></h3><p className="mt-1 text-xs text-muted-foreground">{entity.clientName} · {entity.currency}</p></div></div><dl className="mt-4 grid gap-3 sm:grid-cols-3">{[
    { label: "Pendapatan bulan ini", value: entity.revenueFormatted, hasData: entity.revenue !== null, href: entity.reportHref },
    { label: "Laba bersih bulan ini", value: entity.profitFormatted, hasData: entity.profit !== null, href: entity.reportHref },
    { label: "Kas & bank akhir bulan", value: entity.cashFormatted, hasData: entity.cash !== null, href: workspaceHref(`/clients/${entity.clientId}/trial-balance`, data.scope, { entity: entity.id }) },
  ].map((figure) => <div key={figure.label} className="flex items-start justify-between gap-3 sm:block"><dt className="text-xs text-muted-foreground">{figure.label}</dt><dd className="num text-right text-base font-semibold sm:mt-1 sm:text-left">{figure.hasData ? <Link href={figure.href} aria-label={`${figure.label} ${entity.name}: ${figure.value}; buka rincian`} className="drill">{figure.value}</Link> : <span className="text-xs font-normal text-muted-foreground">Belum ada jurnal</span>}</dd></div>)}</dl>{!entity.hasActivity && <p className="mt-3 text-xs text-muted-foreground">Belum ada jurnal bulan ini. Saldo kas, jika tersedia, berasal dari jurnal sampai akhir bulan.</p>}</article>)}{!data.entities.length && <p className="text-sm text-muted-foreground">Belum ada perusahaan. Tambahkan klien beserta perusahaannya untuk mulai menyiapkan laporan.</p>}<p className="text-xs leading-relaxed text-muted-foreground">Angka laporan yang diunggah tersedia di Dokumen. Unggahan tersebut menjadi bahan analisis dan tidak otomatis menjadi jurnal.</p><Link href={workspaceHref("/documents", data.scope)} className="inline-flex items-center gap-1 text-sm text-primary underline underline-offset-4">Periksa dokumen sumber <ArrowRight className="size-3.5" /></Link></CardContent></Card>;
}
