import Link from "next/link";
import { ArrowRight, CircleAlert, CircleCheck, Clock3 } from "lucide-react";
import type { WorkspaceOverview } from "@/lib/workspace";
import { workspaceHref } from "@/lib/workspace";
import { buttonVariants } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { StatusPill } from "@/components/app/status";
import { Progress } from "@/components/ui/progress";

export function WorkspaceTasks({ data, limit }: { data: WorkspaceOverview; limit?: number }) {
  const tasks = limit ? data.tasks.slice(0, limit) : data.tasks;
  return <Card><CardHeader className="flex flex-row flex-wrap items-center justify-between gap-3"><div><CardTitle role="heading" aria-level={2}>Perlu dikerjakan</CardTitle><CardDescription>Masalah yang menghambat buku didahulukan.</CardDescription></div>{limit && data.tasks.length > limit && <Link href={workspaceHref("/work", data.scope)} className={buttonVariants({ variant: "ghost", size: "sm" })}>Semua pekerjaan <ArrowRight /></Link>}</CardHeader><CardContent><ul className="divide-y">{tasks.map((task) => <li key={task.id} className="flex flex-wrap items-center gap-3 py-4 first:pt-0 last:pb-0"><span className={task.priority === "high" ? "text-review" : "text-muted-foreground"}>{task.priority === "high" ? <CircleAlert className="size-5" aria-label="Prioritas tinggi" /> : <Clock3 className="size-5" aria-label="Pekerjaan berikutnya" />}</span><div className="min-w-0 flex-1"><p className="text-sm font-semibold">{task.title}</p><p className="mt-0.5 text-xs text-muted-foreground">{task.detail}</p></div><Link href={task.href} aria-label={`${task.title} · ${task.detail}`} className={buttonVariants({ variant: "outline", size: "sm" })}>Buka <ArrowRight aria-hidden /></Link></li>)}</ul>{!tasks.length && <p className="flex items-start gap-2 text-sm text-muted-foreground"><CircleCheck className="size-4 shrink-0 text-pass" />{data.clients.length ? "Tidak ada pekerjaan tertunda pada cakupan ini." : "Tambahkan klien untuk mulai menyiapkan buku."}</p>}</CardContent></Card>;
}

export function WorkspaceClose({ data }: { data: WorkspaceOverview }) {
  const { closed, clients } = data.counts;
  return <Card><CardHeader><CardTitle role="heading" aria-level={2}>Kemajuan tutup buku</CardTitle><CardDescription>{data.scope.periodLabel} · penutupan per grup / klien</CardDescription></CardHeader><CardContent className="space-y-4"><div><div className="mb-2 flex justify-between gap-2 text-sm"><span>Klien selesai</span><strong className="num">{closed} / {clients}</strong></div><Progress value={clients ? (closed / clients) * 100 : 0} aria-label={`${closed} dari ${clients} klien selesai tutup buku`} /></div>{data.scope.kind === "entity" && <p className="text-xs leading-relaxed text-muted-foreground">Status mencakup seluruh grup / klien induk perusahaan ini.</p>}<ul className="divide-y">{data.clients.map((client) => <li key={client.id} className="flex flex-wrap items-center justify-between gap-2 py-3"><Link href={client.closeHref} className="inline-flex min-w-0 items-center gap-1 text-sm font-medium hover:text-primary">{client.name}<ArrowRight className="size-3.5 shrink-0" /></Link><StatusPill status={client.state === "LOCKED" || client.state === "READY" ? "PASS" : client.state === "FAIL" ? "FAIL" : "REVIEW"} label={client.label} /></li>)}</ul>{!clients && <p className="text-sm text-muted-foreground">Belum ada klien dalam ruang kerja ini.</p>}</CardContent></Card>;
}

export function WorkspaceFinancials({ data }: { data: WorkspaceOverview }) {
  return <Card><CardHeader><CardTitle role="heading" aria-level={2}>Keuangan per perusahaan</CardTitle><CardDescription>Jurnal yang sudah dibukukan · {data.scope.periodLabel}. Setiap perusahaan memakai mata uangnya sendiri; bukan konsolidasi.</CardDescription></CardHeader><CardContent className="space-y-4">{data.entities.map((entity) => <article key={entity.id} className="rounded-lg border p-4"><div className="flex flex-wrap items-start justify-between gap-2"><div className="min-w-0"><h3 className="text-sm font-semibold"><Link className="inline-flex items-center gap-2 hover:text-primary" href={entity.reportHref}>{entity.name}<ArrowRight className="size-4 shrink-0" /></Link></h3><p className="mt-1 text-xs text-muted-foreground">{entity.clientName} · {entity.currency}</p></div><span className="rounded bg-primary-subtle px-2 py-1 text-xs font-medium text-primary">Dari buku besar</span></div><dl className="mt-4 grid gap-3 sm:grid-cols-3">{[
    { label: "Pendapatan bulan ini", value: entity.revenueFormatted, hasData: entity.revenue !== null, href: entity.reportHref },
    { label: "Laba bersih bulan ini", value: entity.profitFormatted, hasData: entity.profit !== null, href: entity.reportHref },
    { label: "Kas & bank akhir bulan", value: entity.cashFormatted, hasData: entity.cash !== null, href: workspaceHref(`/clients/${entity.clientId}/trial-balance`, data.scope, { entity: entity.id }) },
  ].map((figure) => <div key={figure.label} className="flex items-start justify-between gap-3 sm:block"><dt className="text-xs text-muted-foreground">{figure.label}</dt><dd className="num text-right text-sm font-semibold sm:mt-1">{figure.hasData ? <Link href={figure.href} aria-label={`${figure.label} ${entity.name}: ${figure.value}; buka rincian`} className="text-primary underline underline-offset-4">{figure.value}</Link> : <span className="text-xs font-normal text-muted-foreground">Belum ada jurnal</span>}</dd></div>)}</dl>{!entity.hasActivity && <p className="mt-3 text-xs text-muted-foreground">Belum ada jurnal bulan ini. Saldo kas, jika tersedia, berasal dari jurnal sampai akhir bulan.</p>}</article>)}{!data.entities.length && <p className="text-sm text-muted-foreground">Belum ada perusahaan. Tambahkan klien beserta perusahaannya untuk mulai menyiapkan laporan.</p>}<p className="text-xs leading-relaxed text-muted-foreground">Angka laporan yang diunggah tersedia di Dokumen. Unggahan tersebut menjadi bahan analisis dan tidak otomatis menjadi jurnal.</p><Link href={workspaceHref("/documents", data.scope)} className="inline-flex items-center gap-1 text-sm text-primary underline underline-offset-4">Periksa dokumen sumber <ArrowRight className="size-3.5" /></Link></CardContent></Card>;
}
